[core]
secure = false
secret = 'supersecretpassphrase'
host = '0.0.0.0'
port = 3000
database_url = 'postgres://postgres:postgres@postgres/postgres'

[bot]
enabled = false
prefix = '&'
token = ''
admin = ['']
log_channel = ''
default_uid = 1
hostname = 'example.com'

[shortener]
allow_vanity = true
length = 6
route = '/go'

[uploader]
raw_route = '/r'
length = 6
directory = './uploads'
max_size = 104857600
blacklisted = ['exe']