[core]
secure = false
secret = 'supersecretpassphrase'
host = '0.0.0.0'
port = 3000
database_url = 'postgres://username:password@localhost:5432/db_name'

[bot]
enabled = false
prefix = '&'
token = ''
admin = ['']
log_channel = ''

[uploader]
length = 6
directory = './uploads'
blacklisted = ['exe']