version: '3'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  void:
    image: ghcr.io/alphanecron/void/void:v1
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - './uploads:/void/uploads'
      - './public:/void/public'
      - './logs:/void/logs'
      - './config.json:/void/config.json'
    depends_on:
      - 'postgres'
volumes:
  pg_data:
