name: "Build"
on:
  push:
    branches: [ dev, v0, v1 ]
    paths-ignore:
      - "readme.md"
      - "LICENSE"
      - "config.example.json"
      - ".gitignore"
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - "readme.md"
      - "LICENSE"
      - "config.example.json"
      - ".gitignore"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
      - name: "Setup Node environment"
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: "Restore dependencies"
        id: cache-restore
        uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: "Restore build cache"
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: "Install dependencies"
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: yarn install
      - name: "Build"
        run: yarn build
