name: "Build"
on:
  push:
    branches: [ dev, v0, v1 ]
    paths-ignore:
      - "readme.md"
      - "LICENSE"
      - "config.example.json"
      - ".gitignore"
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - "readme.md"
      - "LICENSE"
      - "config.example.json"
      - ".gitignore"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
      - name: "Setup Node environment"
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: "Get yarn cache directory"
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: "Restore dependencies"
        id: cache-restore
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: "Install dependencies"
        run: yarn install --immutable
      - name: "Build"
        run: yarn build
