name: 'docker push'

on:
  push:
    branches: [ v0 ]
    paths:
      - 'src/**'
      - 'server/**'
      - 'prisma/**'
      - '.github/**'
  workflow_dispatch:
jobs:
  push_to_ghcr:
    name: push to github packages
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: push
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: AlphaNecron/Void/Void
          dockerfile: Dockerfile
          tag_with_ref: true
  push_to_dockerhub:
    name: push to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alphaNecron/void
          dockerfile: Dockerfile
          tag_with_ref: true